format: 
  dashboard:
    logo: logo.svg
    nav-buttons: 
      - icon: github
        href: https://github.com/Alex-and-Noah/pwhl-fantasy-league
    theme:
      - brand
      - styles.scss
    scrolling: true 
    expandable: false